# SwiftLint Configuration for Advent of Code
# https://realm.github.io/SwiftLint/rule-directory.html

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

# Rule configurations
disabled_rules:
  - trailing_comma # Allow trailing commas in arrays

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last

# Customizations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 1 # Allow single-character names (common in AoC)
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id

# Custom reporter (optional)
reporter: "xcode"
